Module2 task1
htmlacademy-react/1370879-six-cities-16 pull request #2
Opened 2024-07-05 15:33 UTC by ministrov

2024-07-05 17:40 UTC, baileys-li approved these changes
Молодец, даже просы написал! :+1: 
Но давай ПР повисит до завтра, есть ещё пару моментов, которые можно сделать

2024-07-05 17:40 UTC, baileys-li commented on src/components/app/app.tsx
> +}
Копипастишь тип, что был). Лучше DRY

2024-07-05 17:40 UTC, baileys-li commented on src/pages/main/main.tsx
> +                isBookmarked={false}
Можно сделать параметр опциональным, чтобы не писать так. Хотя конечно потом, он просто будет в цикле всегда подставляться

2024-07-05 17:40 UTC, baileys-li commented on src/pages/main/main.tsx
> +                  <a href="#">
Это чтобы мне запустить и проверить что сходится?

2024-07-06 09:46 UTC, baileys-li requested changes
Я прочёл, что в этом задании нужна вёрстка других страниц

2024-07-06 09:59 UTC, ministrov commented on src/components/app/app.tsx
> +}
Да че то поленился придумать свой, DRY и к копипасту тоже относится что ли?)

2024-07-06 10:00 UTC, ministrov commented on src/pages/main/main.tsx
> +                  <a href="#">
Не просто забыл удалить)

2024-07-06 10:02 UTC, ministrov commented on src/components/app/app.tsx
> +}
Да че то пленился придумать свой, исправлю, а DRY про копипаст тоже что то говорит?)

2024-07-06 10:03 UTC, ministrov commented on src/pages/main/main.tsx
> +                isBookmarked={false}
Так в итоге че делать? Оставлять так или опционально делать?

2024-07-06 10:03 UTC, ministrov commented on src/pages/main/main.tsx
> +                  <a href="#">
Не , просто забыл удалить)

2024-07-06 10:57 UTC, baileys-li commented on src/components/offer-card/offer-card.tsx
> +      ) : null}
```suggestion
      {isPremium && (
        <div className="place-card__mark">
          <span>Premium</span>
        </div>
      )}
```

2024-07-06 11:02 UTC, baileys-li commented on src/components/offer-card/offer-card.tsx
> +          {isBookmarked ? (
можно упростить, вынести в переменные

2024-07-08 06:00 UTC, merged